CREATE DATABASE DA1_QLNV
USE DA1_QLNV

CREATE TABLE PHONGBAN (
    MAPB VARCHAR(20) NOT NULL PRIMARY KEY,
    TENPB NVARCHAR(100) NOT NULL
);

CREATE TABLE NHANVIEN (
    MANV VARCHAR(20) NOT NULL PRIMARY KEY,
    TENNV NVARCHAR(100) NOT NULL,
    NGAYSINH DATE NOT NULL,
    GIOITINH NVARCHAR(10) NOT NULL,
    EMAIL NVARCHAR(100) NOT NULL,
    DIACHI NVARCHAR(200) NOT NULL,
    MAPB VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES PHONGBAN(MAPB)
);

CREATE TABLE DANGNHAP (
    MANV VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES NHANVIEN(MANV),
    MATKHAU NVARCHAR(100) NOT NULL,
	PRIMARY KEY(MANV)
);

CREATE TABLE CHUCVU (
    MANV VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES NHANVIEN(MANV),
    TENCV NVARCHAR(100) NOT NULL
);

CREATE TABLE LOAINV (
    MANV VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES NHANVIEN(MANV),
    TENLOAINV NVARCHAR(100) NOT NULL
);

CREATE TABLE LUONG (
    MANV VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES NHANVIEN(MANV),
    LUONGCOBAN FLOAT NOT NULL,
    THUONG FLOAT NOT NULL,
    KHAUTRU FLOAT NOT NULL
);

CREATE TABLE KHENTHUONG_KYLUAT (
    MANV VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES NHANVIEN(MANV),
    NGAY DATE NOT NULL,
    LOAI NVARCHAR(100) NOT NULL,
    SOTIEN FLOAT NOT NULL,
    MOTA NVARCHAR(200) NOT NULL
);
CREATE TABLE NGUOIDUNG (
    MANV VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES NHANVIEN(MANV),
    VAITRO NVARCHAR(50) NOT NULL
);
